/**
 * geminiService.js
 * 
 * Handles all interactions with Groq API for Agada (via /api/groq proxy).
 * Keys are managed server-side in Vercel env vars (GROQ_KEY_*).
 * 
 * Two distinct calls are made:
 *   1. extractMedicineFromImage() — Vision model reads the medicine strip photo
 *      and returns structured JSON with brand name, salt, dosage, etc.
 *   2. generateMedicineExplanation() — Text model generates a plain-English
 *      explanation of what the medicine does, its warnings, and OTC status.
 */

const GROQ_PROXY = '/api/groq'

const VISION_MODEL = 'llama-3.2-11b-vision-preview'
const TEXT_MODEL = 'llama-3.3-70b-versatile'

// ─────────────────────────────────────────────
// PROMPT 1: EXTRACTION PROMPT (Vision)
// ─────────────────────────────────────────────
const EXTRACTION_PROMPT = `You are an expert at reading Indian medicine packaging. 
Analyse this medicine strip, box, or label image carefully.

Extract and return ONLY a valid JSON object with these exact keys. 
Do NOT include any text before or after the JSON. No markdown. No explanation. Just the JSON.

{
  "brandName": "exact brand name as printed (e.g., Crocin, Dolo-650, Metformin SR)",
  "saltComposition": "active ingredient(s) with dosage (e.g., Paracetamol 500mg, or Metformin HCl 500mg + Glipizide 5mg)",
  "dosage": "strength as printed (e.g., 500mg, 10mg/5ml)",
  "manufacturer": "manufacturer name exactly as printed",
  "batchNumber": "batch or lot number if visible, else null",
  "expiryDate": "expiry date if visible (format: MM/YYYY or as printed), else null",
  "mrp": "MRP in rupees as a number if visible (e.g., 30.50), else null",
  "tabletCount": "number of tablets/capsules/ml as printed if visible, else null",
  "confidence": "your confidence in this extraction as a percentage (0-100)",
  "extractionNotes": "any important caveats, e.g., 'image blurry', 'partial label visible', or null"
}

Rules:
- If you cannot read the brand name clearly, still provide your best guess and set confidence below 60.
- brandName should be the trade name, not the generic name.
- saltComposition is critical — extract it precisely as it appears, including all active ingredients.
- If multiple medicines appear in the image, extract the most prominent/front-facing one.
- Never fabricate information. If a field is genuinely unreadable, use null.`

// ─────────────────────────────────────────────
// PROMPT 2: EXPLANATION PROMPT (Text)
// ─────────────────────────────────────────────
const buildExplanationPrompt = (saltComposition, brandName) => `
You are a pharmacist explaining a medicine to a patient in simple, clear, friendly English. 
The patient may have low health literacy. Avoid all medical jargon.

Medicine: ${brandName}
Active ingredient(s): ${saltComposition}

Return ONLY a valid JSON object. No markdown. No preamble. Just the JSON.

{
  "whatItDoes": "1-2 sentences in plain language. Example: 'This medicine reduces fever and relieves mild to moderate pain, like headaches or body aches.'",
  "commonUses": ["list", "of", "3-5", "common", "conditions", "it", "treats"],
  "importantWarnings": ["list", "of", "2-4", "key", "warnings", "in", "plain", "language"],
  "isOTC": true or false (true if available Over The Counter, false if prescription required),
  "scheduleH": true or false (true if it requires a doctor's prescription under Schedule H),
  "doNotTakeIf": ["list", "of", "2-3", "key", "contraindications", "in", "plain", "language", "e.g.", "pregnant"],
  "foodInteractions": "brief note on food interactions, or null if none significant",
  "storageInstructions": "brief plain-language storage note (e.g., 'Store in a cool dry place. Keep away from sunlight.')",
  "sourceNote": "AI Estimated — This information is generated by AI and should be verified with a pharmacist or doctor."
}

Keep all text SHORT. Use simple words. Avoid Latin terms. Write as if speaking to a patient at a chemist counter.`

// ─────────────────────────────────────────────
// FUNCTION 1: extractMedicineFromImage
// ─────────────────────────────────────────────

/**
 * Takes a base64-encoded JPEG image of a medicine strip and returns
 * structured extraction data from Groq Vision.
 * 
 * @param {string} base64Image - Base64 encoded image (without data: prefix)
 * @param {string} mimeType - Image MIME type (default: 'image/jpeg')
 * @returns {Promise<Object>} Parsed extraction result
 */
export async function extractMedicineFromImage(base64Image, mimeType = 'image/jpeg') {
  try {
    const res = await fetch(GROQ_PROXY, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({
        model: VISION_MODEL,
        max_tokens: 600,
        temperature: 0.05,
        messages: [{
          role: 'user',
          content: [
            { type: 'text', text: EXTRACTION_PROMPT },
            { type: 'image_url', image_url: { url: `data:${mimeType};base64,${base64Image}` } }
          ]
        }]
      })
    })

    if (!res.ok) {
      const err = await res.json().catch(() => ({ error: res.statusText }))
      return {
        success: false,
        error: err.error || 'API request failed',
        errorType: classifyError(res.status, err),
        data: null,
      }
    }

    const data = await res.json()
    const text = data?.choices?.[0]?.message?.content || ''
    
    // Strip any markdown fences
    const cleaned = text.replace(/```json\n?/g, '').replace(/```\n?/g, '').trim()
    const parsed = JSON.parse(cleaned)

    return {
      success: true,
      data: parsed,
      rawText: text,
    }
  } catch (error) {
    console.error('[Agada] Vision extraction error:', error)
    return {
      success: false,
      error: error.message,
      errorType: 'PARSE_ERROR',
      data: null,
    }
  }
}

// ─────────────────────────────────────────────
// FUNCTION 2: generateMedicineExplanation
// ─────────────────────────────────────────────

/**
 * Takes extracted medicine data and generates a plain-English explanation
 * of what the medicine does, its warnings, OTC status, etc.
 * 
 * @param {string} saltComposition - Active ingredient(s) as extracted
 * @param {string} brandName - Brand name for context
 * @returns {Promise<Object>} Parsed explanation result
 */
export async function generateMedicineExplanation(saltComposition, brandName) {
  const prompt = buildExplanationPrompt(saltComposition, brandName)

  try {
    const res = await fetch(GROQ_PROXY, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({
        model: TEXT_MODEL,
        max_tokens: 800,
        temperature: 0.1,
        messages: [{ role: 'user', content: prompt }]
      })
    })

    if (!res.ok) {
      const err = await res.json().catch(() => ({ error: res.statusText }))
      return {
        success: false,
        error: err.error || 'API request failed',
        errorType: classifyError(res.status, err),
        data: null,
      }
    }

    const data = await res.json()
    const text = data?.choices?.[0]?.message?.content || ''

    const cleaned = text.replace(/```json\n?/g, '').replace(/```\n?/g, '').trim()
    const parsed = JSON.parse(cleaned)

    return {
      success: true,
      data: parsed,
      source: 'AI Estimated',
    }
  } catch (error) {
    console.error('[Agada] Explanation error:', error)
    return {
      success: false,
      error: error.message,
      errorType: 'PARSE_ERROR',
      data: null,
    }
  }
}

// ─────────────────────────────────────────────
// HELPER: Classify errors for user-friendly messages
// ─────────────────────────────────────────────
function classifyError(status, err) {
  if (status === 401) return 'INVALID_API_KEY'
  if (status === 429) return 'QUOTA_EXCEEDED'
  if (status === 400) return 'PARSE_ERROR'
  if (status >= 500) return 'NETWORK_ERROR'
  return 'UNKNOWN_ERROR'
}

export const GeminiErrorMessages = {
  INVALID_API_KEY: 'AI service unavailable. Please try again later.',
  QUOTA_EXCEEDED: 'AI request limit reached. Please try again in a few minutes.',
  SAFETY_BLOCKED: 'The image could not be processed. Please try a clearer photo.',
  PARSE_ERROR: 'AI returned an unexpected response. Please try again.',
  NETWORK_ERROR: 'Network error. Please check your internet connection.',
  UNKNOWN_ERROR: 'Something went wrong. Please try again.',
}
