/**
 * geminiService.js
 * 
 * Handles all interactions with Google Gemini API for Agada.
 * 
 * Two distinct calls are made:
 *   1. extractMedicineFromImage() — Vision model reads the medicine strip photo
 *      and returns structured JSON with brand name, salt, dosage, etc.
 *   2. generateMedicineExplanation() — Text model generates a plain-English
 *      explanation of what the medicine does, its warnings, and OTC status.
 * 
 * Both calls use gemini-1.5-flash for speed and free-tier capacity.
 * 
 * Privacy note: Images are sent directly to Google's API and are NOT stored
 * on any Agada server. Google's API usage policies apply.
 */

import { GoogleGenerativeAI } from '@google/generative-ai'

const API_KEY = import.meta.env.VITE_GEMINI_API_KEY

if (!API_KEY) {
  console.error('[Agada] VITE_GEMINI_API_KEY is not set. Add it to your .env.local file.')
}

const genAI = new GoogleGenerativeAI(API_KEY)

// ─────────────────────────────────────────────
// PROMPT 1: EXTRACTION PROMPT (Vision)
// ─────────────────────────────────────────────
// This prompt is engineered to be extremely explicit about output format.
// We never want Gemini to return free text — we need machine-parseable JSON.
// The prompt instructs Gemini to return ONLY the JSON object, no preamble.
// ─────────────────────────────────────────────
const EXTRACTION_PROMPT = `You are an expert at reading Indian medicine packaging. 
Analyse this medicine strip, box, or label image carefully.

Extract and return ONLY a valid JSON object with these exact keys. 
Do NOT include any text before or after the JSON. No markdown. No explanation. Just the JSON.

{
  "brandName": "exact brand name as printed (e.g., Crocin, Dolo-650, Metformin SR)",
  "saltComposition": "active ingredient(s) with dosage (e.g., Paracetamol 500mg, or Metformin HCl 500mg + Glipizide 5mg)",
  "dosage": "strength as printed (e.g., 500mg, 10mg/5ml)",
  "manufacturer": "manufacturer name exactly as printed",
  "batchNumber": "batch or lot number if visible, else null",
  "expiryDate": "expiry date if visible (format: MM/YYYY or as printed), else null",
  "mrp": "MRP in rupees as a number if visible (e.g., 30.50), else null",
  "tabletCount": "number of tablets/capsules/ml as printed if visible, else null",
  "confidence": "your confidence in this extraction as a percentage (0-100)",
  "extractionNotes": "any important caveats, e.g., 'image blurry', 'partial label visible', or null"
}

Rules:
- If you cannot read the brand name clearly, still provide your best guess and set confidence below 60.
- brandName should be the trade name, not the generic name.
- saltComposition is critical — extract it precisely as it appears, including all active ingredients.
- If multiple medicines appear in the image, extract the most prominent/front-facing one.
- Never fabricate information. If a field is genuinely unreadable, use null.`

// ─────────────────────────────────────────────
// PROMPT 2: EXPLANATION PROMPT (Text)
// ─────────────────────────────────────────────
// This prompt generates the "What is this?" card content.
// Language: plain Hindi-inflected English. No jargon. Built for Tier 3 India.
// ─────────────────────────────────────────────
const buildExplanationPrompt = (saltComposition, brandName) => `
You are a pharmacist explaining a medicine to a patient in simple, clear, friendly English. 
The patient may have low health literacy. Avoid all medical jargon.

Medicine: ${brandName}
Active ingredient(s): ${saltComposition}

Return ONLY a valid JSON object. No markdown. No preamble. Just the JSON.

{
  "whatItDoes": "1-2 sentences in plain language. Example: 'This medicine reduces fever and relieves mild to moderate pain, like headaches or body aches.'",
  "commonUses": ["list", "of", "3-5", "common", "conditions", "it", "treats"],
  "importantWarnings": ["list", "of", "2-4", "key", "warnings", "in", "plain", "language"],
  "isOTC": true or false (true if available Over The Counter, false if prescription required),
  "scheduleH": true or false (true if it requires a doctor's prescription under Schedule H),
  "doNotTakeIf": ["list", "of", "2-3", "key", "contraindications", "in", "plain", "language", "e.g.", "pregnant"],
  "foodInteractions": "brief note on food interactions, or null if none significant",
  "storageInstructions": "brief plain-language storage note (e.g., 'Store in a cool dry place. Keep away from sunlight.')",
  "sourceNote": "AI Estimated — This information is generated by AI and should be verified with a pharmacist or doctor."
}

Keep all text SHORT. Use simple words. Avoid Latin terms. Write as if speaking to a patient at a chemist counter.`

// ─────────────────────────────────────────────
// FUNCTION 1: extractMedicineFromImage
// ─────────────────────────────────────────────

/**
 * Takes a base64-encoded JPEG image of a medicine strip and returns
 * structured extraction data from Gemini Vision.
 * 
 * @param {string} base64Image - Base64 encoded image (without data: prefix)
 * @param {string} mimeType - Image MIME type (default: 'image/jpeg')
 * @returns {Promise<Object>} Parsed extraction result
 */
export async function extractMedicineFromImage(base64Image, mimeType = 'image/jpeg') {
  const model = genAI.getGenerativeModel({ model: 'gemini-1.5-flash' })

  const imagePart = {
    inlineData: {
      data: base64Image,
      mimeType,
    },
  }

  try {
    const result = await model.generateContent([EXTRACTION_PROMPT, imagePart])
    const response = await result.response
    const text = response.text()

    // Strip any markdown fences Gemini might add despite instructions
    const cleaned = text.replace(/```json\n?/g, '').replace(/```\n?/g, '').trim()
    const parsed = JSON.parse(cleaned)

    return {
      success: true,
      data: parsed,
      rawText: text,
    }
  } catch (error) {
    console.error('[Agada] Gemini extraction error:', error)

    // Structured error for UI to handle gracefully
    return {
      success: false,
      error: error.message,
      errorType: classifyGeminiError(error),
      data: null,
    }
  }
}

// ─────────────────────────────────────────────
// FUNCTION 2: generateMedicineExplanation
// ─────────────────────────────────────────────

/**
 * Takes extracted medicine data and generates a plain-English explanation
 * of what the medicine does, its warnings, OTC status, etc.
 * 
 * @param {string} saltComposition - Active ingredient(s) as extracted
 * @param {string} brandName - Brand name for context
 * @returns {Promise<Object>} Parsed explanation result
 */
export async function generateMedicineExplanation(saltComposition, brandName) {
  const model = genAI.getGenerativeModel({ model: 'gemini-1.5-flash' })
  const prompt = buildExplanationPrompt(saltComposition, brandName)

  try {
    const result = await model.generateContent(prompt)
    const response = await result.response
    const text = response.text()

    const cleaned = text.replace(/```json\n?/g, '').replace(/```\n?/g, '').trim()
    const parsed = JSON.parse(cleaned)

    return {
      success: true,
      data: parsed,
      source: 'AI Estimated',
    }
  } catch (error) {
    console.error('[Agada] Gemini explanation error:', error)
    return {
      success: false,
      error: error.message,
      errorType: classifyGeminiError(error),
      data: null,
    }
  }
}

// ─────────────────────────────────────────────
// HELPER: Classify errors for user-friendly messages
// ─────────────────────────────────────────────
function classifyGeminiError(error) {
  const message = error.message?.toLowerCase() || ''

  if (message.includes('api_key') || message.includes('401')) {
    return 'INVALID_API_KEY'
  }
  if (message.includes('quota') || message.includes('429')) {
    return 'QUOTA_EXCEEDED'
  }
  if (message.includes('safety') || message.includes('blocked')) {
    return 'SAFETY_BLOCKED'
  }
  if (message.includes('json') || message.includes('parse')) {
    return 'PARSE_ERROR'
  }
  if (message.includes('network') || message.includes('fetch')) {
    return 'NETWORK_ERROR'
  }
  return 'UNKNOWN_ERROR'
}

export const GeminiErrorMessages = {
  INVALID_API_KEY: 'Gemini API key is missing or invalid. Please check setup instructions.',
  QUOTA_EXCEEDED: 'AI request limit reached. Please try again in a few minutes.',
  SAFETY_BLOCKED: 'The image could not be processed. Please try a clearer photo.',
  PARSE_ERROR: 'AI returned an unexpected response. Please try again.',
  NETWORK_ERROR: 'Network error. Please check your internet connection.',
  UNKNOWN_ERROR: 'Something went wrong. Please try again.',
}
