import React from 'react'
import { Link } from 'react-router-dom'

export default function DisclaimerPage() {
  return (
    <div className="max-w-lg mx-auto px-4 py-6">
      <h1 className="text-2xl font-black text-agada-navy mb-4">Medical Disclaimer</h1>

      <div className="space-y-4 text-sm text-gray-700">
        <div className="bg-yellow-50 border border-yellow-200 rounded-2xl p-4">
          <p className="font-bold text-yellow-800 mb-1">⚠️ This is not medical advice.</p>
          <p className="text-yellow-700">
            Agada is an information and awareness tool. It does not provide medical diagnoses, 
            treatment recommendations, or prescriptions. Always consult a licensed doctor, 
            pharmacist, or healthcare professional before making any medication decision.
          </p>
        </div>

        <div className="bg-white rounded-2xl p-4 shadow-card">
          <h3 className="font-bold text-agada-navy mb-2">About CDSCO Verification</h3>
          <p className="leading-relaxed">
            Agada queries the CDSCO drug registry in real time against publicly available government data. 
            A "VERIFIED" result means the brand name was found in the registry as of the last database 
            update. It does not constitute a guarantee that the specific physical product you are holding 
            is authentic. Visual inspection cannot replace laboratory testing.
          </p>
        </div>

        <div className="bg-white rounded-2xl p-4 shadow-card">
          <h3 className="font-bold text-agada-navy mb-2">About AI-Generated Information</h3>
          <p className="leading-relaxed">
            Medicine explanations are generated by Google Gemini AI and are labelled "AI Estimated." 
            AI can make errors. This information is provided for general awareness only. 
            It should not be relied upon for clinical decisions. Always verify with a licensed pharmacist.
          </p>
        </div>

        <div className="bg-white rounded-2xl p-4 shadow-card">
          <h3 className="font-bold text-agada-navy mb-2">About Generic Medicines</h3>
          <p className="leading-relaxed">
            Information about Jan Aushadhi generics and NPPA price ceilings is sourced from 
            official government portals. While generics are required by law to be bioequivalent 
            to branded medicines, individual patient responses can vary. Consult your doctor before 
            switching from a branded to a generic medicine.
          </p>
        </div>

        <div className="bg-white rounded-2xl p-4 shadow-card">
          <h3 className="font-bold text-agada-navy mb-2">Reporting Suspected Fakes</h3>
          <p className="leading-relaxed">
            If you suspect a medicine is counterfeit, do not consume it. Contact:
          </p>
          <ul className="mt-2 space-y-1">
            <li>• CDSCO Helpline: <strong>1800-180-3024</strong> (free)</li>
            <li>• State Drug Control Authority</li>
            <li>• Your local police</li>
          </ul>
        </div>
      </div>

      <div className="text-center mt-6">
        <Link to="/" className="bg-agada-green text-white px-6 py-3 rounded-xl font-bold text-sm hover:bg-agada-green-dark transition-colors">
          ← Back to Scanner
        </Link>
      </div>
    </div>
  )
}
